### ISSUE TITLE
User can upload profiles into editor and uploaded profile is now in list of available profiles

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#10]
Profiles are not limited by schema (i.e. can have "BIBFRAME extensions") and still be loaded into editor for use.

**Comment by michelleif** [comment]
NOTE: have not specified where in the "list of available profiles" the uploaded profile is added: alphabetically? last?

**Comment by michelleif** [comment]
this is tracked in UAT ticket for Milestone 3 so closing this
