### ISSUE TITLE
Profile Editor respond with only JSON to user

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia#100]
Part of the proposed Sinopia process is for the profile editor to respond with the profile as JSON that the user can then save locally or copy to somewhere like Github. This needs to be configured for the Sinopia-installed profile editor.

**Comment by jgreben** [comment]
This means we also need to disable the Save and Delete buttons in the profile editor, and only allow them to export the data as JSON (review the difference between Verbose and Brief Export).
