### ISSUE TITLE
Set up profile-editor to deploy to ECS

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia#101]
- [ ] Need to add load-balancer in front of ECS?
- [x] Determine / setup access URL (i.e. profile-editor.sinopia.org or some such) Added ticket #https://github.com/LD4P/sinopia_profile_editor/issues/15 for this item

**Comment by ndushay** [comment]
@jermnelson will fix this ticket / close it in favor of new ones.

**Comment by jermnelson** [comment]
Removed docker (captured in ticket [#1 Profile Editor](https://github.com/LD4P/profile-edit/issues/1) and [#8 Profile editor](https://github.com/LD4P/profile-edit/issues/8)
