### ISSUE TITLE
Admin homepage

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#110]
Admin homepage where PO can grant bibliographic editor access to users and assign them to groups

**Comment by astridu** [comment]
![23_adminpage.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6c7b5d3aa13600133488f8/125516c66e82c728ace21e0d46bac7a522868ea081f9be44a11fbcd6395428792c07b7692ac7b62aee132e56590e18ac435f0b46fcf98878f4b03875885919f1c32f0e2a92624cf5f2d75dad0ba821834584b3b88a4fc3ea3d23e38e8f492c53.png)

**Comment by michelleif** [comment]
agreed we are using command line for Work Cycle 1. moving to Future.

**Comment by michelleif** [comment]
not planning on doing group assignments in current grant
