### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#116]
The footer that will appear at the bottom of all of Sinopia:
1. Profile Editor
2. Homepage
3. Registration pages
4. Bibliographic Editor

**Comment by astridu** [comment]
Created a separate ticket for this so I could reference this ticket in all the other branding tickets since requirements for this are not finalized yet.

Text only (Footnote text font, color 797268, center aligned on page): "Sinopia is a project of Linked Data for Production 2 (LD4P2), funded by the Andrew W. Mellon Foundation."

**Comment by michelleif** [comment]
in Profile Editor now available on dev, the "Linked Data for Production" phrase is hyperlinked to the wrong URL; it should go to www.ld4p.org, it's going to http://sinopia-pe.dev.sul.stanford.edu/#

**Comment by jermnelson** [comment]
@astridu have you heard anything from TC about the CC 4.0 graphic and language for the footer?

**Comment by astridu** [comment]
He still needs to get approval from Mimi and Mike, but I told him we were going with what I emailed him until he says otherwise. I'm 90% certain what we have will be fine.
