### ISSUE TITLE
UI and requirements for error states

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#117]
1. Fields validated after they are submitted.
2. If error is found, highlight the field in red and place error message directly under field or to the right, depending on space. 
3. Error message should contain info on what happened and how to fix it. for ex, We couldn't connect to the server. Please try again later. OR This feature is under maintenance. Please see our release notes for when it will be available.
4. User errors vs. System errors
5. Field level error https://invis.io/5YNLDND63KF#/316667110_Profile
6. Page level error https://invis.io/5YNLDND63KF#/316593318_Registration
7. Font size = 14pt, color = B1040E
8. Red outline of box = B1040E
9. Box background shade = F2DEDE

**Comment by michelleif** [comment]
@jermnelson I think this is done, as far as we're going to do it. Please close if you agree.
