### ISSUE TITLE
Wait states

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#119]
For any actions that take longer than 2 seconds to load, display an indeterminate wait state. See https://material.io/design/components/progress-indicators.html#circular-progress-indicators for 2 basic animated wait states (progress bar, spinner). Either of those would work.

**Comment by michelleif** [comment]
@jermnelson @justinlittman is this something we want to consider? or we hope that nothing takes that long to load!

**Comment by justinlittman** [comment]
This is premature optimization until we hit any actual wait states. And when we do, can determine whether to address the wait state or display a progress indicator. So closing (for now).
