### ISSUE TITLE
QA lookups in editor

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#12]
when profile specifies, a field should do a "type-ahead" type lookup against QA sources including but not limited to:

- wikidata
- id.loc.gov
- LC Works
- Geonames
...

**Comment by michelleif** [comment]
Cornell is gathering info about lookups here: https://wiki.duraspace.org/display/LD4P2/LD4P2%3A+Consolidating+information+about+lookups

**Comment by ndushay** [comment]
See also LD4P/sinopia_editor#10

**Comment by michelleif** [comment]
this works (except for multiple sources for one lookup, and that is documented elsewhere)
