### ISSUE TITLE
research deployment practices re: terraform, AWS

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia#124]
e.g., figure out whether devs should be able to deploy directly to prod w/o going through ops, etc

**Comment by jmartin-sul** [comment]
met with @rsmith11 yesterday and mostly paired to get me up to speed on terraform basics, DLSS terraform practices, AWS credentials and web UI, etc.  we talked briefly about what we might do for deployment practices, but mostly punted on that since that's the first topic of a larger meeting on wednesday of next week.

IIRC, rob said ops wouldn't find it burdensome to have to do all the prod deployments, unless deployments were being requested multiple times per day.

rob also said ops has no objection to devs being able to do stage deployments themselves, at will.

**Comment by jmartin-sul** [comment]
no one's actively working on this at the moment AFAIK.  i'm not sure if we have a documented procedure for deployment in production (or if we even think we've fully figured it out).

moving this out of the In Progress column, under the assumption that we'll revisit to finalize and document how we deploy in prod... sometime before the end of this work cycle.

**Comment by jermnelson** [comment]
@jmartin-sul should we close or label this as future for now? For this work-cycle, I don't think Ops wants devs to directly interact with production.

**Comment by jmartin-sul** [comment]
yeah, let's close this for now
