### ISSUE TITLE
Sinopia Dashboard Page

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#128]
Based on feedback from the October LD4P2 conference, cohort users wanted access to a number of resources on one page such as:
1. latest bug fixes, features, news
2. maintenance window
3. links to meetings and technical stuff
4. timeline with progress towards milestones
5. links back to BFF and profile editor
![24_dashboard.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6c7b5d3aa13600133488f8/125516c66e82c728ace21e0d46bac0a5278390a18de6be51a01fbcd6395428792c07b7692ac7b62aee132e56590e18ac435f0b46fcf98878f4b03875885919f1c32f0e2a92624cf5f2d75dad0ba822894584b3b88a4fc3ea3c22ef8c864f2c53.png)

**Comment by jermnelson** [comment]
@astridu is there a priority list of what resources/reporting the cohort desire? Given our tight deadlines and the likely amount of work required to implement some of these dashboard features like the bug fixes feed, maintenance schedule, and work cycle timeline graphic (meeting notes, technical links, and latest features shouldn't be too hard as they are manually added/edited) along with the implementation of the dashboard was not part of our initial time estimates for the project plan.

**Comment by astridu** [comment]
The 2 most important things are to show the timeline and the PCC section. Everything else is secondary. However, we can always figure out somewhere else to post (duraspace/wiki page?) if we run out of time to implement this page. Maybe I can talk to Michelle about creating a page ourselves and then having our 'official' dashboard scoped out in a later work cycle.

**Comment by michelleif** [comment]
planning on putting this info in github wiki, will close ticket when i'm done

**Comment by michelleif** [comment]
we are using the github wiki as the primary source of help information, and we have the help menu and the sinopia homepage at our disposal to push out other important info
