### ISSUE TITLE
[WIP] Update links in 'Help and Resources' panel

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#136]
This is a WIP. Please do not work on this yet. 

> Sinopia User Dashboard: coming soon

> Contact Us
E-mail Sinopia Group: coming soon
Join Slack Channel: https://ld4.slack.com/messages/#sinopia

> Training Resources
Intro to Profile editor: coming soon
Intro to Bibliographic editor: coming soon
Troubleshooting: coming soon

> Website Usage
Policies: coming soon
Terms of Use: coming soon
Request Account: coming soon

> External Identifier Services and Vocabularies
Art & Architecture Thesaurus: http://www.getty.edu/research/tools/vocabularies/aat/
Discogs: https://www.discogs.com/search/
Geonames: http://www.geonames.org/
IMDB: https://www.imdb.com/
ISNI: http://www.isni.org/
ISSN Portal: https://portal.issn.org/
LC Linked Data Service: http://id.loc.gov/authorities/names.html
MusicBrainz: https://musicbrainz.org/
ORCID: https://orcid.org/
RDA Registry: https://www.rdaregistry.info/
Thesaurus of Graphic Materials: http://www.loc.gov/pictures/collection/tgm/
Thesaurus of Geographical Names: http://www.getty.edu/research/tools/vocabularies/tgn/index.html
VIAF: https://viaf.org/
Wikidata: https://www.wikidata.org/wiki/Wikidata:Main_Page

> Other External Resources
Google Books: https://books.google.com/
Google Scholar: https://scholar.google.com/
Google Translate: https://translate.google.com/
Share-VDE: http://www.share-vde.org/sharevde/clusters?l=en

**Comment by michelleif** [comment]
handled by LD4P/sinopia_editor#338
