### ISSUE TITLE
User Stories: Registration and Login

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#157]

**Comment by michelleif** [comment]
Story 1: user without account visits Sinopia homepage and wants to register for account.
1. user goes to Sinopia homepage sinopia.io. No login required to see this page. User reads page, decides they want an account.
2. user has way to request an account (supplies name, email, institution) (button opens another window, form on page, whatever)
3. account request goes somewhere to be approved by admin
GO TO: Story 3: admin manages account request

Story 2: user attempts to open Linked Data Editor, whether from sinopia.io home page, or from Profile Editor, or by going directly to Linked Data Editor URL:
1. user sees prompt to log in or to request account. if user requests account go to Story 1; otherwise:
2. user logs in. login successful, they see Linked Data Editor page. if login unsuccessful, prompted to login again, or given way to retrieve password

Story 3 :admin manages account request
1. admin receives account request
2. admin either:
a. approves account and then user gets notified by email that account is ready (password is provided, or user is asked to create password? doesn't matter)
b. sends email to user to get more info, then approves
c. sends email to user to say sorry, you are not allowed to use this, and doesn't create account

Story 4: admin creates account directly
1. admin creates account for a user, supplying name, email, institution
2. user receives email confirming that account is ready (password is provided, or user is asked to create password? doesn't matter)

Story 5: admin deletes account

Story 6: QUESTION: how/when do users get put into groups?

**Comment by jmartin-sul** [comment]
some implementation ideas we've considered for the the user creation/modification workflow:
* account creation is entirely self service, but edit access is blocked by need for manual addition to groups.
  * workflow
    1. user visits login page, sings up for account
    2. user is sent confirmation email, clicks link
    3. we get notified that a user has signed up (e.g. cognito post-confirmation hook triggers lambda that notifies us).
    4. someone (e.g. @michelleif) adds the user's webid to the appropriate ACLs of the appropriate groups.
  * pros/cons
    * this would allow us to use the default cognito login and signup page 
    * this would likely be lower effort to implement
    * this *should* prevent edit access by unverified users, since we believe the group ACL definitions should prevent editing of resources by users who haven't been added to a group ACL yet.  however, since the new user account would be able to login to the system, there is the vague worry that this provides an opportunity for privilege escalation if there are access control bugs elsewhere in the system.
* the "signup page" actually just notifies us that a user wants to signup, and we create the account manually
  * workflow _will finish filling in_
  * pros/cons _will finish filling in_
* we figure out a way to create the user in a disabled state, so that even after they confirm, they can't login until we manually activate their cognito account.
  * workflow _will finish filling in_
  * pros/cons _will finish filling in_

**Comment by michelleif** [comment]
re this option "account creation is entirely self service, but edit access is blocked by need for manual addition to groups", another con is that user will not know if they are set up to start using Sinopia until we manually notify them that they have been added to appropriate groups (unless there is some automatic notification built in from Trellis?)

**Comment by jmartin-sul** [comment]
@michelleif, nope, no automatic notification for group addition.  we could probably set that up by leveraging trellis' linked data notifications, but it would definitely take development effort that we haven't budged for yet.

**Comment by jmartin-sul** [comment]
re:
> re this option "account creation is entirely self service, but edit access is blocked by need for manual addition to groups", another con is that user will not know if they are set up to start using Sinopia until we manually notify them that they have been added to appropriate groups (unless there is some automatic notification built in from Trellis?)

@michelleif clarified that what she's looking for is notification when the user's account is created.

also: @michelleif is fine with a very manual setup process where user emails us or submits a form (or institution submits a list of their users).  then michelle creates account for the user manually.

**Comment by jmartin-sul** [comment]
tentative decision:  go with first option (cognito default signup page).  see how that goes as we implement it.  we think that'll be our lowest LOE approach for implementation.

**Comment by michelleif** [comment]
closing this as the UAT things are captured in the UAT Milestone 3 ticket
