### ISSUE TITLE
default cognito confirmation email looks real phishy (fixed except for the "from" email address)

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia#159]
current email is super generic, just for testing, but we should flesh it out so it doesn't look so plain and suspicious.

this will be done in terraform, but we don't wire the terraform repo to this waffle board since it spans projects.  so this is a proxy ticket in the sinopia repo.

<img width="395" alt="screen shot 2019-01-31 at 11 12 25 am" src="https://user-images.githubusercontent.com/7741604/52079992-a3a84680-254b-11e9-8c9e-c36a33bac607.png">
<img width="987" alt="screen shot 2019-01-31 at 11 12 43 am" src="https://user-images.githubusercontent.com/7741604/52079993-a440dd00-254b-11e9-9861-2fc5cf83b144.png">

**Comment by michelleif** [comment]
screenshot of current confirmation request email:
![2_please confirm account request](https://user-images.githubusercontent.com/23069165/53452544-6a41ea00-39d6-11e9-8a3c-25379ebae4b9.png)

1) can we change the "from" address from no-reply@verificationemail.com to sinopia_admin@stanford.edu?

2) Change body of the email to:
Thank you for requesting a new Sinopia account. To confirm your request, click here [add link]. Next, a Sinopia administrator will grant you permission to create and edit data. You will receive an email from a Sinopia administrator as soon as this permission has been granted. Please contact [sinopia_admin@stanford.edu](mailto:sinopia_admin@stanford.edu) with questions.

**Comment by michelleif** [comment]
think this is fixed, need to test

**Comment by michelleif** [comment]
body of message looks good.

can the "from" address be changed so it doesn't look phishy? current: "no-reply@verificationemail.com"; change to "sinopia_admin@stanford.edu" if possible

**Comment by michelleif** [comment]
see above question re the "from" email. if it's easy to change, please do, if not, please comment and close the ticket.

**Comment by jmartin-sul** [comment]
not sure.  likely easy to change, but i think this just hasn't been something we've had an opportunity to look into yet at all, hence the lack of response so far.

**Comment by michelleif** [comment]
k i'm going to move this to future and change the title to reflect the part about the email address
