### ISSUE TITLE
Editor usage analytics

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#16]
might also mean capturing some information about users in that registration step (i.e. institution). 

who uses it, from where, to create how many things, etc.

Generate reports of number of users, number of sets of data (entities / resources cataloged; forms filled; etc), etc.

**Comment by michelleif** [comment]
from sinopia team meeting: need to delineate which metrics we promise and how much identity / institutional info we need to capture

**Comment by michelleif** [comment]
will be partly satisfied by https://github.com/LD4P/sinopia/issues/231

**Comment by michelleif** [comment]
will be partially satisfied by #231 
anything further can be dealt with after work cycle 1

**Comment by michelleif** [comment]
we can do this manually with viewing # of users in cognito, devs can query trellis for # of resources created, closing this ticket. if there are specific metrics requests we can open a new ticket.
