### ISSUE TITLE
Use authority list from QA server for lookupConfig

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia#162]
In both the sinopia_editor and the profile_editor switch to fetching the qa lookup config from the qa_Server. See: https://github.com/LD4P/qa_server/issues/51

This will not include the LOC List lookup configs so part of this will be combining the two sets of json.

**Comment by michelleif** [comment]
see https://github.com/LD4P/sinopia_profile_editor/issues/212 for new approach

**Comment by michelleif** [comment]
ignore above erroneous reference to 212

**Comment by michelleif** [comment]
@jermnelson @justinlittman is this worth doing?

**Comment by justinlittman** [comment]
Current approach is adequate.
