### ISSUE TITLE
AWS Cognito UI Customization

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#171]

**Comment by jgreben** [comment]
All I did here was to add the exiting (cropped) header logo and change the header background color:
![screen shot 2019-02-25 at 11 06 03 am](https://user-images.githubusercontent.com/3093850/53361832-8d449f00-38ed-11e9-9f4b-e08f3c1ed93a.png)

@astridu we could use a slightly higher resolution logo. I enlarged the logo that I found on the google drive so it's a bit blurry.

**Comment by jgreben** [comment]
After story time convo w/ @astridu this is how it looks now:

<img width="360" alt="screen shot 2019-02-25 at 1 35 23 pm" src="https://user-images.githubusercontent.com/3093850/53370315-47460600-3902-11e9-8155-66a44e713bb4.png">

**Comment by astridu** [comment]
Looks good. I don't think you need the background on the letters. For just the 'SINOPIA' text, you can use this file: https://drive.google.com/open?id=16E1mFdPcoFdN7-nxCEZhIxordpU5vTPE

**Comment by jgreben** [comment]
ok @astridu here it is now:
![Uploading Screen Shot 2019-02-25 at 1.40.37 PM.png…]()

The background is #D1C6B9 which I got using an eyedrop tool on the graphic. LMK if there's a specific html color code you want.

**Comment by astridu** [comment]
Perfect! Thank you.

**Comment by jgreben** [comment]
There is currently no support for the UI customizations via terraform, but there is an open issue requesting support for it:
https://github.com/terraform-providers/terraform-provider-aws/issues/3634

**Comment by jgreben** [comment]
Waiting for verbiage from Michelle to finish customizing the form and the messages that it displays.

**Comment by michelleif** [comment]
(1) Changes for registration confirmation screen (current screen here):
![3_registration confirm](https://user-images.githubusercontent.com/23069165/53452362-f30c5600-39d5-11e9-8b4a-ac5246b439e6.png)
. Replace existing text with:
"Your Sinopia user account is now active. Next, a Sinopia administrator will grant you permission to create and edit data. You will receive an email from a Sinopia administrator as soon as this permission has been granted. Please contact sinopia_admin@stanford.edu with questions."

(2) Low priority. On Account request screen (current screen here)
<img width="434" alt="1_newaccountrequest" src="https://user-images.githubusercontent.com/23069165/53452422-18995f80-39d6-11e9-8eaa-4eeef46e3f75.png">
change "Sign up with a new account" to
"Sign up for a new account"

**Comment by jgreben** [comment]
@michelleif I misspoke about being able to customize these things via AWS. The only kind of text that is customizable are the email messages sent from AWS. One day in the future when we decide to code our own login/logout forms using the AWS SDK we can use your form text.

**Comment by michelleif** [comment]
np. thanks for investigating.
