### ISSUE TITLE
Email Confirmation

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#172]
AWS Confirmation email text

**Comment by rsmith11** [comment]
For the email verification message, right now I've updated it so that the email Subject is "Sinopia User Registration" and the email message is:
```
Thank you for signing up for Sinopia. In order to complete your signup process, please click the following code: 

Click Here 

Once completed, our Administrators will still need to add you to the appropriate group to edit resources. They will be in touch shortly.
```
Once they click on the verification link, a email is get sent to the administrator(s) with the following Subject:
```
The following Sinopia user has been created:

Username: rsmith11
Email: <rsmith11@xxxxx.com>

Please add them to the necessary group in Trellis.
```
All of this is currently in Terraform.

**Comment by jermnelson** [comment]
Closing
