### ISSUE TITLE
increase max allowable length of email address for Sinopia user account

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#180]
if you try to create a new Sinopia account with an email address longer than 20 chars you get an error and can't continue. increase allowable length so this doesn't happen

(NOTE: this is ticket for Terraform repo)

**Comment by ndushay** [comment]
I think this might be a simple matter of updating https://github.com/sul-dlss/terraform-aws/blob/sinopia-cognito-email/organizations/development/sinopia/cognito.tf#L33

**Comment by ndushay** [comment]
Per wikipedia:  "The format of email addresses is local-part@domain where the local part may be up to 64 characters long and the domain may have a maximum of 255 characters."   so 320 (counting the `@` char).  @jgreben will make this change in his WIP sinopia-cognito-email  terraform-aws branch

**Comment by jgreben** [comment]
Fixed by 
https://github.com/sul-dlss/terraform-aws/pull/330
