### ISSUE TITLE
Terraform apply wipes out all of the users and UI customizations

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia#186]
We will need to export and re-import the active users before running a `terraform apply` that will do a tear-down and re-build of the sinopia-cognito instance.

This repo provides a cli tool to backup the users:
https://github.com/mifi/cognito-backup
 - user export example, supposedly:
   - https://github.com/mifi/cognito-backup/blob/master/cli.js#L37-L65
   - https://github.com/mifi/cognito-backup/blob/master/cli.js#L83-L95

AWS has instructions for creating an import job and then using `curl` to upload a CSV file of users:
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-creating-import-job.html

**Comment by michelleif** [comment]
moving to future because we don't plan to "terraform apply" on PRD for this Work Cycle

**Comment by michelleif** [comment]
@jermnelson @justinlittman ok to close?

**Comment by michelleif** [comment]
@jermnelson @justinlittman ok to close?

**Comment by jermnelson** [comment]
This is still a problem if we need to rebuild Cognito using Terraform (but we haven't needed to do this in the past two work-cycles)

**Comment by jermnelson** [comment]
Closing, devs moving away from TF work.
