### ISSUE TITLE
provision local VM for ACL management

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia#192]
updating sinopia ACLs requires user lookup, which requires AWS CLI tools and private AWS creds.

this is a pain even for devs to provision, so to make life easier for our non-developer admin(s), we'd like to:
- [ ] spin up a local VM for ACL management
- [ ] add `futo` (@michelleif) to the K5 login list
- [ ] deploy the https://github.com/LD4P/sinopia_acl/ app to the VM
- [ ] install the [AWS CLI tool](https://aws.amazon.com/cli/) (which the sinopia ACL util will rely on for user lookup)
- [ ] provision the necessary AWS credentials on the VM, similar to what's described in our terraform documentation.

this will allow michelle to just get a kerb ticket (using `kinit` on her laptop), ssh into the VM, and use our sinopia server ACL editing tool.  no need for her to provision AWS credentials locally, install our ACL editing tool, install the AWS CLI, etc.  "easy"!  :slightly_smiling_face:

**Comment by jmartin-sul** [comment]
see https://github.com/LD4P/sinopia_server/issues/79#issuecomment-475142864 for the AWS CLI commands we'd be using

**Comment by ndushay** [comment]
John and I found an aws sdk npm package that lets us get the "sub" for the webid given a username, so we won't need to do it via AWS CLI.  We *think* this means we do NOT need the AWS CLI installed on the new VM.  🤷‍♀️

**Comment by rsmith11** [comment]
If we don't need the AWS CLI on the VM, then do we even need the VM at all?  What else was going to run on it?

**Comment by jmartin-sul** [comment]
the SDK will need the same credentials the CLI would need, so preventing the user from having to set that stuff up on their machine still seems like a big win to me.

if installing the CLI is relatively easy, i'd go for it.  i can see it being useful, esp for debugging.  we for sure had some trouble figuring out how to do the stuff in JS that we knew how to do more easily with the CLI tool.

**Comment by jmartin-sul** [comment]
i assume the JS SDK is itself wrangling credentials and making ReST calls to AWS API endpoints (which is to say we don't _think_ the JS SDK needs the CLI to do its thing, but i at least am not 100% sure about that, maybe @ndushay has already investigated that and is sure about it).

**Comment by mjgiarlo** [comment]
I guess my question is: if there's no CLI to run for Michelle to do ACL management, who will use this VM and for what? If devs or ops will handle one-sy, two-sy ACL changes here and there, do we get enough value out of this VM to provision it, or is it sufficient for devs/ops folks to patch the occasional ACL from their laptops?

________________________________

**Comment by jmartin-sul** [comment]
ah, yes, fair point.  i was still assuming there'd be a CLI tool for michelle to run, but of course that's not a sure thing anymore.  so yeah, if that's not the case, and if it ends up just being devs and ops folks doing this, i'd think the VM would be unnecessary.

is the no CLI tool decision made at this point?  is that part of the 2-3 pm meeting today, or is that meeting just about whether there will be groups at all (with the assumption that authorization won't be by group, and everyone can edit everything).

**Comment by mjgiarlo** [comment]
@jmartin-sul :speech_balloon: 
> ah, yes, fair point. i was still assuming there'd be a CLI tool for michelle to run, but of course that's not a sure thing anymore. so yeah, if that's not the case, and if it ends up just being devs and ops folks doing this, i'd think the VM would be unnecessary.

:+1: 
 
> is the no CLI tool decision made at this point? is that part of the 2-3 pm meeting today, or is that meeting just about whether there will be groups at all (with the assumption that authorization won't be by group, and everyone can edit everything).

My understanding is that we decided to cut scope on the ACL work, and chose not to build out the CLI (late last week? Monday?). Is that your recollection, @ndushay @jermnelson ?

**Comment by jmartin-sul** [comment]
sounds right to me, in retrospect.  i think i did learn that on monday, but stale info had not yet been evicted fully from the cache when when i wrote that comment 🙂

**Comment by mjgiarlo** [comment]
@jmartin-sul it sounds like we have a bit more discussing to do re: groups and ACLs. shall we wait 'til that wraps and then revisit this issue? (potentially closing it if we are sure that the CLI is out of scope.)

**Comment by jmartin-sul** [comment]
sounds good to me!

**Comment by ndushay** [comment]
@jmartin-sul @mjgiarlo @rsmith11   do we not need the VMs because we need to be able to send commands to the production AWS server, which we cannot reach from our laptops?  

We may not need the CLI command, necessarily, but we need the code to use AWS credentials to get info from the production AWS pool about user "sub" or uuids, at a minimum.

**Comment by mjgiarlo** [comment]
@ndushay I'm not sure about how we're using security groups in AWS. With RIALTO's setup, we were able to reach AWS from anywhere as long as we used the Stanford VPN in full-tunnel mode. Dunno if that's what Sinopia is/will be doing. 

I suspect we need @rsmith11 to answer this one. Or @jermnelson ?

**Comment by ndushay** [comment]
Closing this.  From standup discussion:

- Rob will open trellis for world access via https port 443. 
    - Web browsers using sinopia_editor need access
- Not currently envisioning Michelle doing WAC work for this work cycle
    - Not a big deal to spin up VMs later if we need them.
