### ISSUE TITLE
Define password policy for Cognito users

### ISSUE THREAD

**Issue by rsmith11** [LD4P/sinopia#194]
Currently we only require user passwords to be a minimum of 8 characters; it can be any string of 8 characters (88888888 for example).  This would seem too basic from a security standpoint, and should perhaps be changed to a stronger enforcement.  The options to enforce in Cognito are:

- Require Numbers
- Require Special Characters
- Require uppercase letters
- Require lowercase letters

Amazon recommends at least passwords with at least 8 characters, lowercase, uppercase, and numbers for greater security.

**Comment by michelleif** [comment]
@rsmith11 PRD now requires lower case letter, upper case letter and number, so can we close this ticket?
