### ISSUE TITLE
Add content for any WIP notation in github pages documentation.

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#195]
Multiple points in the current Sinopia documentation have WIP or work in progress placeholders. These should all have some text and at least reflect the current path and technology choices we're making for the MVP.

**Comment by michelleif** [comment]
@jermnelson ok to close?

**Comment by jermnelson** [comment]
Should be; I don't think there are any outstanding areas that still
have a WIP placeholder.
