### ISSUE TITLE
Redux Basic Tutorial 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#198]
Self-paced learning Redux by going through the [Basic Tutorial](https://redux.js.org/basics/basic-tutorial)

- [x] @jmartin-sul 
- [x] @ndushay 
- [x] @mjgiarlo
- [x] @peetucket
- [ ] @justinlittman
- [ ] @jcoyne
- [ ] @aaron-collier 

Also look at these technologies:

https://react-redux.js.org/introduction/basic-tutorial
this was a great brief description, too:  https://blog.isquaredsoftware.com/presentations/workshops/redux-fundamentals/react-redux.html#/0
- [ ] @jmartin-sul 
- [x] @ndushay 
- [x] @mjgiarlo
- [x] @peetucket
- [ ] @justinlittman
- [ ] @jcoyne
- [ ] @aaron-collier 

https://github.com/reduxjs/reselect
https://redux.js.org/recipes/computing-derived-data

- [ ] @jmartin-sul 
- [ ] @ndushay 
- [x] @mjgiarlo
- [ ] @peetucket
- [ ] @justinlittman
- [ ] @jcoyne
- [ ] @aaron-collier

**Comment by ndushay** [comment]
@mjgiarlo too?

**Comment by ndushay** [comment]
@mjgiarlo @jmartin-sul I found this really helpful (and short!)

https://redux.js.org/introduction/three-principles

**Comment by mjgiarlo** [comment]
@ndushay thank you! I'll be digging into this soon.

**Comment by mjgiarlo** [comment]
Finished reading through all this stuff. Unassigning myself.

**Comment by ndushay** [comment]
I'm pretty sure we're all redux conversant enough now, so I'm closing it.
