### ISSUE TITLE
CEDAR / IndexData dev collab questions

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia#2]
Upon selection of an editor codebase for starting, reach out to appropriate people (CEDAR or IndexData & LC) re: development collaboration scope.

**Comment by cmh2166** [comment]
We now know this is BFE. LC is on the regular Sinopia / QA calls. @michelleif @jermnelson a next step might be to reach out to IndexData to chat informally both about FOLIO & their BFE enhancements work overlaps. I have developer contacts there I can reach out to, if helpful. Will someone take on scheduling that?

**Comment by jermnelson** [comment]
I've also reached out to Kirk at Library of Congress as well.

**Comment by cmh2166** [comment]
Yeah, and he's on the QA / Sinopia stuff, so we have LC covered. Reaching out to Index Data though could be very helpful.

**Comment by ndushay** [comment]
@cmh2166 will reach out to IndexData;  closing this ticket.
