### ISSUE TITLE
Ops needs for backing up Cognito user pools

### ISSUE THREAD

**Issue by mjgiarlo** [LD4P/sinopia#207]
- [x] Create dedicated S3 bucket to hold backup data in the form of JSON files and grant Cognito admin user read/write access (**blocking** https://github.com/LD4P/sinopia_user_backup/issues/1)
  - [x] in development environment
  - [x] in staging environment
  - [x] in production environment
- [x] Create Fargate task based on `ld4p/sinopia_user_backup:latest` image (**blocked by** https://github.com/LD4P/sinopia_user_backup/issues/1)
  - [x] in development environment
  - [x] in staging environment
  - [x] in production environment
- [x] Launch above task via CloudWatch events, scheduled to run thrice a day (roughly midnight, 8am, and 4pm)
  - [x] in development environment
  - [x] in staging environment
  - [x] in production environment

**Comment by rsmith11** [comment]
I'm guessing, but I assume you need the following variables passed:

COGNITO_USER_POOL_ID
COGNITO_CLIENT_ID
AWS_REGION
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
S3_BUCKET

Anything else?

**Comment by mjgiarlo** [comment]
@rsmith11 the sinopia_user_backup container only needs the following env vars:

* `AWS_ACCESS_KEY_ID`
* `AWS_REGION`
* `AWS_SECRET_ACCESS_KEY`
* `COGNITO_USER_POOL_ID`
* `S3_BUCKET`

**Comment by rsmith11** [comment]
The default timezone for CloudWatch events is UTC.  It was originally mentioned in previous ticket that the runtimes should be at `(midnight, 8am, 4pm)`.  Should that be Pacific Time, or keep it UTC?

**Comment by mjgiarlo** [comment]
@rsmith11 :speech_balloon:
> The default timezone for CloudWatch events is UTC. It was originally mentioned in previous ticket that the runtimes should be at `(midnight, 8am, 4pm)`. Should that be Pacific Time, or keep it UTC?

UTC is A-OK. It doesn't much matter when the task runs, as long as it runs three times a day. Thanks!

**Comment by rsmith11** [comment]
Cognito backup container deployed in all environments and setup to run at specified times.

**Comment by mjgiarlo** [comment]
@rsmith11 Awesome! Now that all the boxes are ticked, I think we can close the issue. What do you say?

cc: @jermnelson
