### ISSUE TITLE
Add CloudWatch alerts/alarms to avoid being surprised by OOM killers

### ISSUE THREAD

**Issue by mjgiarlo** [LD4P/sinopia#216]
Trellis in dev has been killed because the container ran out of memory. It would be ideal to be notified about OOM issues as those conditions arise.

(Not going to assign you, @rsmith11, until/unless you're available to take this on. Feel free to self-assign once that's the case.)

**Comment by rsmith11** [comment]
Trellis, the homepage, and the profile editor all have alarms setup so if their healthchecks fail (service down or high memory usage), alerts will be sent to sinopia-devs@lists
