### ISSUE TITLE
Setup Trellis backup for memento files in EFS

### ISSUE THREAD

**Issue by rsmith11** [LD4P/sinopia#217]
Currently Trellis memento files are stored in a shared EFS volume mounted to the ECS containers.  There needs to be a plan to backup the files in case there's a need to restore.  Will need to work out when to backup and for how long to retain backup files.

**Comment by mjgiarlo** [comment]
Assigning to @rsmith11 since this is marked as in progress. Hope that's OK, Rob.

**Comment by rsmith11** [comment]
Using AWS Backup service to take daily snapshots and retain backups for 90 days.
