### ISSUE TITLE
In configuring forms and fields, use any ontology or vocabulary

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#22]
here: any ontology can be used for the RDF output of these forms (i.e. not limited to BIBFRAME only)

**Comment by ndushay** [comment]
already in profile editor functionality.

**Comment by michelleif** [comment]
reopening this pending UAT confirmation that you can use any class/property and it comes out properly in RDF from Linked Data Editor

**Comment by michelleif** [comment]
this is tracked in UAT ticket for Milestone 4, so closing
