### ISSUE TITLE
Set default resource(s) as subject for a form

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#23]
A3: Specify what ontology class this form describes

Questions:
- [ ] default resource that a form is asserting statements against (default resource == subject)
- [ ] how to configure those default resource(s) for a form, and do other grouping

**Comment by michelleif** [comment]
Believe this is what the "Resource URI" field is for, but keeping this open until this is confirmed.

**Comment by michelleif** [comment]
this is handled by ResourceURI
