### ISSUE TITLE
PO access to see how many users / which users we have

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#231]
Is there a way I can see the user accounts that have been established on each of the 3 environments? This is for knowing how uptake is going.

**Comment by jcoyne** [comment]
@michelleif do you have access to the AWS console?

**Comment by michelleif** [comment]
I don't know. how can I check?

**Comment by jcoyne** [comment]
If you do you can go to https://us-west-2.console.aws.amazon.com/cognito/users/?region=us-west-2#/pool/us-west-2_ilMQW0M0R/users?_k=etwzxg

**Comment by michelleif** [comment]
@rsmith11 how do I get an Amazon account so I can see the Cognito user list for Sinopia in all 3 environments?

**Comment by rsmith11** [comment]
I'll need to create a user account for you in Terraform.  Once created, I'll work with you on the logon process.

**Comment by michelleif** [comment]
thanks @rsmith11 I assigned this issue to you, lmk when my account is ready

**Comment by rsmith11** [comment]
Is there any user management you want to do (deleting users, etc) or is this just a view only?

**Comment by michelleif** [comment]
as long as someone else has the ability to delete users, then I am ok with view-only. we talked about needing to delete a user only if it turned out there was a malicious user. adding @jermnelson in case I'm overlooking something. are there other user management tasks that are possible?

**Comment by michelleif** [comment]
@rsmith11 i'm able to login and switch to DevelopersRole per https://github.com/sul-dlss/terraform-aws/wiki/AWS-DLSS-Dev-Env-Setup
then I go to Cognito and tried to look at User Pool and Identity Pool but nothing was there. what do I do to see list of users?

**Comment by rsmith11** [comment]
When you go to the main Cognito page as the DeveloperRole and click on 'Manage User Pools' do you see a user pool called 'sinopia-development-pool'?

**Comment by michelleif** [comment]
no I get this:
<img width="1161" alt="Screen Shot 2019-07-24 at 11 46 41 AM" src="https://user-images.githubusercontent.com/23069165/61819862-b7e94400-ae08-11e9-978b-b54edb39cfa9.png">

**Comment by rsmith11** [comment]
Thanks for the screen shot.  You'll need to change your region from `Ohio` to `Oregon` (us-west-2)

**Comment by michelleif** [comment]
ok I can see DEV users now thanks!
when I try to switch to staging per the https://github.com/sul-dlss/terraform-aws/wiki/AWS-DLSS-Dev-Env-Setup#other-useful-roles-available-to-developers instructions I must be doing something wrong
<img width="942" alt="Screen Shot 2019-07-25 at 11 22 25 AM" src="https://user-images.githubusercontent.com/23069165/61898703-ca2db580-aece-11e9-9be3-3d28e577ee55.png">

**Comment by rsmith11** [comment]
The account should be `sul-dlss-staging`.  You are missing an "l" in dlss in the screenshot.

**Comment by michelleif** [comment]
doh! sorry!

**Comment by michelleif** [comment]
I am able to see users on all 3 environments now. thank you!
