### ISSUE TITLE
Research Cloudwatch alerts for scheduled container runs

### ISSUE THREAD

**Issue by rsmith11** [LD4P/sinopia#233]
We have 3 scheduled tasks that run containers (acl, cognito user backup, and reindex) but while they report back to Cloudwatch logs on their success/failure, there are no alerts associated with them.  Need to research to see if there is a way to tie alerts into the scheduled tasks, or find a way to have containers report back success or failure.

**Comment by michelleif** [comment]
@jermnelson @justinlittman still relevant?
