### ISSUE TITLE
write DevOpsDocs

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia#236]
we need to write at least one entry for sinopia here:
https://github.com/sul-dlss/DevOpsDocs/tree/master/projects

typically, we do one entry per application, and so that would indicate to me that we want individual pages for:
- [ ] sinopia_editor
- [ ] sinopia_profile_editor
- [ ] sinopia_acl
- [ ] sinopia_server

we can spawn individual tickets in the appropriate repos as we break off those subtasks.

as a last resort, we could do one whole sinopia entry.  i'd vote against doing that if possible, because it will likely be confusing and overwhelming, when the point of devopsdocs is to provide an easy primer for someone unfamiliar with an application.  and though the four applications listed above all work together to support the editor, they are all individual applications with separate deployments.

**Comment by jcoyne** [comment]
if "one entry per application" then the application is "sinopia".  All of those other things are services.  I'd just do one dev ops doc, as someone unfamiliar should have a landing page that explains that there are 4 important services to check.

**Comment by michelleif** [comment]
@jermnelson @justinlittman  is this complete?

**Comment by jermnelson** [comment]
Waiting on  Rob to review draft
