### ISSUE TITLE
Batch load multiple records

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#248]
Load RDF lets you load up statements to a Resource Template, creating a new resource

some users asked to be able to do this in a batch, to load multiple sets of statements, all corresponding to the same Resource Template, to create a bunch of new resources at once

**Comment by michelleif** [comment]
have asked Alberta for more info and will ask Harvard as well (who requested the batch load RDF)

**Comment by michelleif** [comment]
rated relatively low on sept 2019 prioritization by cohort

**Comment by jcoyne** [comment]
This seems like an ETL rather than an editor task.  Why would they need Sinopa at all? Why not just put the resources in Trellis?

**Comment by justinlittman** [comment]
This is in the Sinopia repo, as implementation is not determined.

**Comment by michelleif** [comment]
@jermnelson we can batch load with API right? if so, let's close this
