### ISSUE TITLE
Map form values to input types

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#25]
A6: Specify data type for field: 
1. URI/IRI, 
2. string, 
3. date, 
4. year, 
5. integer, 
6. decimal, 
7. duration (hh-mm-ss), 
8. boolean?, 
9. cartographic such as lat/long.?, 
10. pick-list (dropdown or radio or checkbox). 
11. image 

NOTE: definition of allowed values is listed as separate requirement

Later work: prioritizing list above for implementation planning (i.e. which first)

**Comment by michelleif** [comment]
LC Profile Editor allows specification of the following types: 
literal, resource, lookup, target, list

For Sinopia, need to confirm that each of these work as expected in Editor
