### ISSUE TITLE
export all resource descriptions from a given group

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#254]
get export of all descriptions created in Sinopia for a single *group* (when a resource description is saved, user puts it in a group, by institution or other group, like PCC)

format: TBD. N-triples?
request and delivery method: originally envisioned that user makes request from UI and get the file delivered; simpler set up is: we publish a downloadable export every week or so *of an export from each group*, and user takes it as needed

see https://github.com/LD4P/sinopia_exporter/

**Comment by michelleif** [comment]
weekly, to S3 publicly accessible bucket

**Comment by justinlittman** [comment]
Folded into #253 for easier ticket management.
