### ISSUE TITLE
search a single institution's Share-VDE dataset from Search tab

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#255]
search a single institution's Share-VDE dataset (on Search tab) and view results

need to give user a way to specify which institution's set to search (ld4p/sinopia_editor#1377)

Display the following information about each result (ld4p/sinopia_editor#1388)
    - Label
    - Class (if there's more than one, display them all)
    - QA source / dataset (when searching a single institution, all the results will be from the same source, unless we distinguish among those 3 superwork, work, instance datasets). 

DECISIONS: 
- Each institution has 3 datasets: superwork, work, and instance. We decided to have one search that searches them all. Later we could add a sub-authority choice, if needed by users.

QUESTIONS:
- What actions can user perform on the results? See more information? Open in a resource template?
- What other information does QA give back that we might want to display?
- Pagination: is it useful to show how many pages of results there are and allow user to go to final page?

**Comment by astridu** [comment]
@michelleif How many individual external data sources could there be? If there are dozens, I would probably do a different control than a dropdown, but if it's < 25, then the dropdown would work.
![image](https://user-images.githubusercontent.com/42216982/64978957-866e8100-d86b-11e9-9c34-bc3b2d1a7265.png)
![image](https://user-images.githubusercontent.com/42216982/64979033-ae5de480-d86b-11e9-81b9-b3a1c4d21735.png)

**Comment by michelleif** [comment]
@astrid please add updated design with no "download" instruction, thank you!

**Comment by justinlittman** [comment]
Here's a search result from QA:
![Screen Shot 2019-09-17 at 7 04 24 AM](https://user-images.githubusercontent.com/588335/65036525-993f8f00-d919-11e9-9e04-72b9966f8dac.png)

Note that the result may include multiple titles and types. How should this be handled?

Also, I've verified that superwork, work, and instance are all subauthorities, so can be searched at once for an institution.

Also, superworks, works, and instances all appear to have titles.

Also, note that there is not a modified date in the result (as shown in the mockup).

Also, what is the ID column? In the current Sinopia search it is next a number as shown in the mockup but is that what is intended?

**Comment by michelleif** [comment]
@astridu could you update design? "modified date" is relevant only for the Sinopia search #90. Do we need ID?

**Comment by michelleif** [comment]
@justinlittman are there multiple values because we are searching superwork, work and instance simultaneously?

**Comment by justinlittman** [comment]
No. Because a resource can be multiple types of things. Apparently, the same resource can be a Work, a Superwork, and a Hub.

**Comment by astridu** [comment]
I updated the mockup above. Also, I removed ID. When I first created this mockup, I thought users might want to have the list ordered, but haven't heard any requests for that.

**Comment by justinlittman** [comment]
A few comments:
* Our latest strategy (as of a few minutes ago) is to search a QA authority that includes all ShareVDE resources. This means that the "Data Source" column no longer makes sense, as it will be the same for all resources in the results list.
* Is it worth displaying the resource URI?

**Comment by michelleif** [comment]
even if there's one authority for all sources, won't we know which institution it came from?

**Comment by michelleif** [comment]
@astridu more changes per today's QA/Sinopia meeting:
1) we will use the "label" provided by QA instead of "Title". That way it doesn't matter whether something has a title or not, or whether something has more than one title. (QA concatenates the titles into a label)
2) Under "class" there can be more than one value, and each value will probably be a URI, not just a class name. We want to show all the values, so we don't have to worry about picking which one is best. In the sample data included above, that would mean showing all three values under Type.
Could you update the mockup to show how these two things will look?

**Comment by justinlittman** [comment]
I would not expect to know that, unless it is added to the authority. However, that puts us in the position of having to handle some QA authorities different that others, which is doable, but suboptimal. I'd recommend implementing the simplest way and then see if users request changes.

**Comment by michelleif** [comment]
i'm going to move these notes to the ticket for searching multiple Share-VDE sources #256

**Comment by astridu** [comment]
I updated the mockup above. Is that correct?

**Comment by michelleif** [comment]
@justinlittman should we remove Data Source column then since we aren't supporting searching more than one source right now?

**Comment by justinlittman** [comment]
@michelleif Makes sense to remove for now and can revisit later.

**Comment by michelleif** [comment]
@justinlittman in answer to question "Is it worth displaying the resource URI?", I think yes, if the user could click on it and then see more information. Would that be the case?

**Comment by justinlittman** [comment]
Can you elaborate what you mean by "click on it and then see more information"? My thought is that it would be a link to the resource in the editor, like the title.

**Comment by michelleif** [comment]
but we are talking about external resources, that we know will not necessarily open nicely in the Editor. I'm wondering if the external URI would take the user to an actual page that would give more info than what we are showing in search results (which is going to be label plus type)

**Comment by michelleif** [comment]
@astridu question came up about search results design: should we use the same "copy" icon we will use in Sinopia results for the user to open the QA "record" in a Resource Template? and then don't have the result label hyperlinked? (because there's nothing else you can do with the result?). I'll schedule a time with you to discuss.

**Comment by justinlittman** [comment]
Also @michelleif @astridu, need design for selecting resource template when user wants to open a QA resource in editor.

**Comment by astridu** [comment]
@michelleif Re: the interaction to open a QA record in a Resource Template-- I think the interaction should be the same (hyperlink the name of the record). When you open it, the save/preview/copy/download icons will be disabled so it's clear to the user that they can't perform any actions on the record.

**Comment by astridu** [comment]
@michelleif @justinlittman Re: design for selecting resource template when user opens a QA resource in editor. I had designed this as an overlay. Once user clicks the record they want to open, an overlay appears which prompts the user to select a resource template, or just use the one we suggest. Will this work? 
![image](https://user-images.githubusercontent.com/42216982/65913718-37edd600-e385-11e9-9d46-87efdcfbc76a.png)

**Comment by justinlittman** [comment]
So we don't have a "by default". One possibility (for a separate ticket) might be to remember the last choice the user made for the same types.
________________________________

**Comment by michelleif** [comment]
so for searching Sinopia we are proposing to have the title be hyperlinked and when you click it you open the resource you found, and then a separate icon for "Copy" and when you click that, you open a copy of the resource

but with non-Sinopia (QA) search results, you can't really "open" the existing resource. all you can do is copy. so that's why I'm suggesting that the label of the external search results *not* be hyperlinked, because clicking on that means "open". instead we would just have the "copy" icon because all you can do is copy.

thoughts?

**Comment by justinlittman** [comment]
That works, but here's a slight alternative.

Don't link the title in either case. Instead use icons for edit (for example https://fontawesome.com/icons/edit?style=solid) and copy, where edit and copy are available for Sinopia and only copy for QA. This makes the actions clearer to the user (whereas the linked title is ambiguous).

**Comment by michelleif** [comment]
oooo, i like that

**Comment by astridu** [comment]
That works for me.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/66066286-17955700-e4fe-11e9-8e56-07588ea2098e.png)

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/66066326-30057180-e4fe-11e9-9f3a-d2016cac4cc9.png)
