### ISSUE TITLE
search Discogs from search tab

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#257]
from Search tab, search the Discogs source

@astridu please add design that shows how user would select the Discogs source (NOTE: searching more than one QA source at a time is out of scope, other than the choice to search "all Share-VDE datasets"

QUESTION: what do we display for Discogs results? is it a different display than Share-VDE results?

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/64979121-dfd6b000-d86b-11e9-890d-784397f13f8d.png)

**Comment by justinlittman** [comment]
Looks like discogs results from QA don't have titles:
![Screen Shot 2019-09-17 at 10 08 29 AM](https://user-images.githubusercontent.com/588335/65049148-4d014880-d933-11e9-8836-3da99fb4eeb3.png)

so that is going to be problematic.

**Comment by michelleif** [comment]
we decided to use the label, as for other sources.

**Comment by michelleif** [comment]
see ld4p/sinopia_editor#1420
