### ISSUE TITLE
add ability to select destination resource template from Load RDF tab

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#258]
this allows prototyping of #95 

let user select from list of available Resource Templates

NOTE: @justinlittman already has this prototyped

**Comment by astridu** [comment]
Spoke with @justinlittman and decided to try putting instructions in the dialogue box as the watermark so users can see what we want them to enter. 
![image](https://user-images.githubusercontent.com/42216982/65915894-332b2100-e389-11e9-929d-8bcd04a75db4.png)

**Comment by justinlittman** [comment]
Actually, it is without brackets for Base URI (but no need to change mockup).
