### ISSUE TITLE
load RDF into user-selected Resource Template and display statements that don't match

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#259]
from Load RDF tab, copy entered data into the Resource Template the user selects (see #258) and if there are statements that don't "fit", tell the user and show those "remainder" statements in a useful way. 

Useful way might be:
    - text box
    - triples shown in columns so it's easy to select and copy part of the triple
    - a way to drag stuff into open fields
    - any URIs in the remainder data are clickable so you can explore further

NOTE: @justinlittman already has above prototyped

**Comment by justinlittman** [comment]
![2019-09-20_0956](https://user-images.githubusercontent.com/588335/65460512-11c5b480-de20-11e9-9d9c-505e5a7d0068.png)

**Comment by michelleif** [comment]
feedback from demo at user group meeting:
1) throw away (or condense) any internal system identifiers like Share-VDE URIs, which are meaningless here?
2) JSON-LD instead of triples (also see https://github.com/LD4P/sinopia_editor/issues/1355)
3) give a shortened form of the property, like bf:property (then we would need to know the prefix)
2) could disregard some triples, like MarcKey (though we want to build something all-purpose and not get into specifics of what to discard from which external source)

**Comment by michelleif** [comment]
re-opening this because we still want to do:
ld4p/sinopia_editor#1355
need astrid to design
