### ISSUE TITLE
Copy Sinopia resource to start a new resource

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#263]
This wasn't originally called out explicitly as a success criterion at the beginning of Work Cycle 1, but it is something users assume will be available: if you can copy external data into a new resource (#95) , why not Sinopia data?

The request is to be able to pick an existing Sinopia resource (either from Sinopia search results on Search tab or while editing/looking at that resource in the Edit tab), and copy that resource, so the result is a new resource, in the same Resource Template, no URI until you Save the new resource.

**Comment by michelleif** [comment]
@astridu could you add here (1) your design for the Sinopia search results with a "copy" icon next to each result? and (2) the revised Preview / Copy / Save buttons that will go at top of Edit tab when viewing/editing a resource? (leave off Download button for now, that will be ticketed separately)

**Comment by astridu** [comment]
1. Sinopia Search Results with a 'copy' icon. 
![image](https://user-images.githubusercontent.com/42216982/65532736-39b12880-deb1-11e9-8e56-9828d3aed5de.png)

2. Revised Preview/Copy/Save
![image](https://user-images.githubusercontent.com/42216982/65532805-5b121480-deb1-11e9-9da8-d4aba032da94.png)

Detail of buttons in inactive and hover state.
![image](https://user-images.githubusercontent.com/42216982/65533283-310d2200-deb2-11e9-8163-af79fc1afa00.png)

**Comment by michelleif** [comment]
@astridu thank you could you replace with search results design where there is no download menu option? we are not doing that yet.
also did we decide the icons were better or the buttons with words? plus please remove download button. that will be ticketed separately.

**Comment by astridu** [comment]
1. no download menu
![image](https://user-images.githubusercontent.com/42216982/65538250-cb259800-debb-11e9-9372-62f0203fef91.png)

2. No download icon: we decided on icons with a hover state that says what the icon does.
![image](https://user-images.githubusercontent.com/42216982/65538171-9e718080-debb-11e9-8706-63d12111d596.png)

![image](https://user-images.githubusercontent.com/42216982/65538201-aa5d4280-debb-11e9-864a-efdaf3a9de56.png)

**Comment by jcoyne** [comment]
@astridu we're currently using the free set of icons in FontAwesome: https://fontawesome.com/icons?d=gallery&q=docum&m=free  I don't see one that looks like the preview icon.  Can you select something different or tell us what icon set you are using?

**Comment by astridu** [comment]
Sorry about that. We can use fa-eye. Not as nice, but it works. 
![image](https://user-images.githubusercontent.com/42216982/66065377-15ca9400-e4fc-11e9-96e0-f518d244473c.png)
