### ISSUE TITLE
Add environment to header

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia#268]
For staging and dev, add the environment next to Linked Data Editor in the header.

See https://github.com/LD4P/sinopia_editor/issues/1298#issuecomment-529706022 but note this is only to add the text, not changing any styling depending on environment.

**Comment by peetucket** [comment]
Suggested path:

- add to Config (https://github.com/LD4P/sinopia_editor/blob/master/src/Config.js)
- add arg to Dockerfile https://github.com/LD4P/sinopia_editor/blob/master/Dockerfile)
- set as build-arg in Circle config (https://github.com/LD4P/sinopia_editor/blob/master/.circleci/config.yml#L62 and L78 and L79)
- fetch value and add to component for display

**Comment by peetucket** [comment]
Do we want to show a label when in production too?  Presumably it would make sense to show something in stage or dev, but leave blank in -prod?

**Comment by justinlittman** [comment]
That's correct @peetucket. Blank in prod.
