### ISSUE TITLE
Document Cognito restore

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia#271]
Since it is not a normal DB restore

**Comment by justinlittman** [comment]
cc @jmartin-sul @mjgiarlo 

Probably belongs in DevOpsDocs.

**Comment by mjgiarlo** [comment]
@jmartin-sul might you be inclined to take this on next week?

**Comment by jmartin-sul** [comment]
@mjgiarlo happy to!

**Comment by jmartin-sul** [comment]
created a wiki entry specifically for this:
https://github.com/LD4P/sinopia_server/wiki/How-to-deal-with-the-Cognito-user-pool-getting-dropped-and-re-created

and some supporting documentation about Cognito and JWT stuff, linking out to more authoritative/detailed docs:
https://github.com/LD4P/sinopia_server/wiki/Authentication-and-Authorization-in-Trellis
https://github.com/LD4P/sinopia_editor/wiki/Login-and-Authentication-to-Trellis

also updated the relevant section in DevOpsDocs and submitted a PR there.

**Comment by justinlittman** [comment]
Awesome, thanks @jmartin-sul.
