### ISSUE TITLE
Some titles are not displaying in Sinopia search results

### ISSUE THREAD

**Issue by sfolsom** [LD4P/sinopia#280]
We have templates that are still using the embedded form pattern. We loaded into Sinopia a CornellSinatra45:Work template that has an embedded CornellSinatra45:Instance template. The CornellSinatra45:Instance template also links back to the CornellSinatra45:Work template. See: https://github.com/LD4P/sinopia_sample_profiles/blob/master/cohort-profiles/Cornell/Cornell%20Sinatra%20BIBFRAME%202.0%20Sound%20Recording-Analog%2045.json

We're finding CornellSinatra45:Work titles index if the template is accessed directly when creating data. When the CornellSinatra45:Work is accessed indirectly (embedded in CornellSinatra45:Instance) the Work titles aren’t producing search results. CornellSinatra45:Work titles are displaying as values in search results if the template was accessed directly.

CornellSinatra45:Instance titles are not searchable or displaying in the Search tab whether created by accessing the template directly, or from within CornellSinatra45:Work. The Instances, if created by accessing the template directly are showing up when searching using an '*', but the title isn't displaying.
![Screen Shot 2020-02-27 at 10 40 01 AM](https://user-images.githubusercontent.com/8257258/75464626-73e98f00-5955-11ea-883f-711415648fb2.png)

E.g. https://trellis.sinopia.io/repository/cornell/7c24c836-0390-452e-85b5-6bfe8025512d

**Comment by jermnelson** [comment]
Created bug ticket https://github.com/LD4P/sinopia_editor/issues/2090 that is the underlying cause of this error. Closing this issue in favor the bug report in the Sinopia Editor repository.
