### ISSUE TITLE
Grant Infra team access to all NPM packages

### ISSUE THREAD

**Issue by mjgiarlo** [LD4P/sinopia#282]
Please grant all infrastructure team members write/publish access to all Sinopia NPM packages:

* [x] https://www.npmjs.com/package/sinopia_acl
* [x] https://www.npmjs.com/package/sinopia_profile_editor
* [x] https://www.npmjs.com/package/sinopia_server
* [x] https://www.npmjs.com/package/sinopia_editor
* [x] https://www.npmjs.com/package/sinopia_indexing_pipeline

Usernames of team members:

- [x] jermnelson
- [x] justincoyne
- [x] justinlittman
- [x] mjgiarlo
- [x] peetucket
- [x] jgreben
- [x] jmartin-sul
- [x] ndushay
- [x] amcollie

**Comment by mjgiarlo** [comment]
@peetucket @ndushay @jcoyne @aaron-collier @jmartin-sul Please add your npmjs.com usernames to the description of this ticket and then it will be actionable for @jermnelson

**Comment by jermnelson** [comment]
Everyone should be added to the Sinopia NPM packages. Please let me know if you have any problems.

**Comment by peetucket** [comment]
worked for me
