### ISSUE TITLE
Sinopia Editor Refactor

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#284]
This refactoring of Sinopia Editor will focus on these areas:

## Simplify Redux state
**Completed** Move from complex hierarchy of resource templates with resource models to key-based approach

## Simplify React Components
Reduce number of components, remaining components should be functional (not React classes) using React hooks

## Testing refactoring/simplification
UI components tested through “integration” tests, minimize individual unit tests for React components. Non-UI unit tests remain for Javascript classes and functions. 

## Investigate Trellis Replacement with MongoDB

**Comment by michelleif** [comment]
@jermnelson done?

**Comment by jermnelson** [comment]
Closed.
