### ISSUE TITLE
Replace or Improve Cognito

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#285]
Currently Sinopia uses AWS [Cognito](https://aws.amazon.com/cognito/) for user authentication, access, and management. While Cognito has proved usable, we may need a more general user management approach in order to support user-based customization and other authentication methods like LDAP or Shibboleth. Any replacement must support the creation of JSON Web Tokens ([JWT](https://jwt.io/)).  

Given the time constraints for the 2020 Q3 work-cycle, revisiting and investigating how we improve the use of  Cognito within Sinopia may be the best option instead of a full-replacement of Cognito in the Sinopia stack.

**Comment by jermnelson** [comment]
Possible alternatives to Cognito:
- [Passport.js](http://www.passportjs.org/)
- [You don't need passport.js - Guide to node.js authentication](https://softwareontheroad.com/nodejs-jwt-authentication-oauth/) more of rolling your own in node.js.

**Comment by michelleif** [comment]
closing in favor of #2901
