### ISSUE TITLE
Fix or Replace Trellis use of ActiveMQ

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#287]
In the current Sinopia stack, the Trellis LDP publishes [messages](https://github.com/trellis-ldp/trellis/wiki/Notifications) to an AWS ActiveMQ queue that is then picked up by the [Indexing Pipeline](https://github.com/ld4p/sinopia_indexing_pipeline) that then either adds/updates/deletes the resource document in the Elasticsearch cluster. Occasionally for the past year-and-a-half, Trellis stop connecting to ActiveMQ which halts all Elasticsearch indexing activity. Trellis now supports [AMQP](https://www.trellisldp.org/docs/trellis/current/apidocs/org/trellisldp/amqp/package-summary.html) or an alternative is to use [Camel](https://github.com/trellis-ldp/camel-ldp-recipes/tree/master/elasticsearch) for direct indexing into Elasticsearch.

**Comment by mjgiarlo** [comment]
@jermnelson :speech_balloon: 
> In the current Sinopia stack, the Trellis LDP publishes [messages](https://github.com/trellis-ldp/trellis/wiki/Notifications) to an AWS ActiveMQ queue that is then picked up by the [Indexing Pipeline](https://github.com/ld4p/sinopia_indexing_pipeline) that then either adds/updates/deletes the resource document in the Elasticsearch cluster. Occasionally for the past year-and-a-half, Trellis stop connecting to ActiveMQ which halts all Elasticsearch indexing activity. Trellis now supports [AMQP](https://www.trellisldp.org/docs/trellis/current/apidocs/org/trellisldp/amqp/package-summary.html) or an alternative is to use [Camel](https://github.com/trellis-ldp/camel-ldp-recipes/tree/master/elasticsearch?rgh-link-date=2020-07-28T17%3A16%3A54Z) for direct indexing into Elasticsearch.

I have no attachment to ActiveMQ but I am wondering if we have a sense of what causes the disconnects. My worry is that we put effort into swapping out ActiveMQ for an AMQP-based back-end (or Camel) only to have them suffer from the same disconnects.

**Comment by justinlittman** [comment]
ActiveMQ connections are notoriously flacky because they maintain an active connection. In other words, I think the problem is with the ActiveMQ stack (exasperated by running in AWS, where the network is a black box), not anything Trellis specific.

That being said, nothing to guarantee won't encounter problems with AMQP or Camel. The Camel connector for ElasticSearch might be worth a look, as at least for communicating with ES, is straight HTTP.

**Comment by jermnelson** [comment]
Closing as Trellis is being depreciated in favor of MongoDB which doesn't use ActiveMQ.
