### ISSUE TITLE
Save search even if user navigates away from search page

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#289]
If user searches on search page and then navigates away from the page, user has to search again when they return to the search page. Is there a way to save that search if user hits browser back or clicks the 'Search' tab.

**Comment by justinlittman** [comment]
This is super annoying ...

@astridu Should a clear button be added to the search page?

**Comment by jermnelson** [comment]
Issue moved to [LD4P/sinopia_editor #2334](https://github.com/LD4P/sinopia_editor/issues/2334) via [**ZenHub**](https://www.zenhub.com/)
