### ISSUE TITLE
Limit a field's allowed values to any term from one or more published vocabularies

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#29]
A10: Limit a field's allowed values to any term from one or more published vocabularies

Question: Is this lookup or validation; look-up is feasible (i.e. only look up from LCNAF); validation is harder (i.e. how to check something provided is in LCNAF).

**Comment by michelleif** [comment]
this is for lookup, not for validation. example: profile creator says: in this field, you can use values from AAT, but only from the Materials branch of AAT.
Another example: profile creator says: you can use one of these 5 subject headings from LCSH

**Comment by michelleif** [comment]
awaiting support of having multiple sources for one lookup (support on Linked Data Editor side)

**Comment by michelleif** [comment]
this is covered by LD4P/sinopia_editor#348

**Comment by michelleif** [comment]
previously had commented that this was covered by https://github.com/LD4P/sinopia_editor/issues/348, it's not. but in any case, this is supported by QA subauthorities, so if QA has a lookup that is, say, to "materials facet only of AAT" then we support this.
