### ISSUE TITLE
Personalizations

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#293]
Allow users to log in and see personalized information on a dashboard such as:
1. Saved searches for records and resource templates
2. Last 10 records modified
3. Last 10 resource templates use
4. Statistics on number of records completed or modified

**Comment by jermnelson** [comment]
@astridu what would the URL be for this functionality? https://sinopia.io/dashboard?

**Comment by michelleif** [comment]
most of this is done. @astridu could you make a new ticket for user statistics if that is still desired?
