### ISSUE TITLE
Personalization when user logs in

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#296]
When user logs in, we should know who they are and have the ability to show personalizations throughout the site (like their name, for example).

**Comment by justinlittman** [comment]
What are the requirements beyond the user's name?

**Comment by astridu** [comment]
Just putting the user's name on the dashboard and the ability to know that it's them and which institution they are from. I put the other requirements into separate tix.

**Comment by justinlittman** [comment]
Thanks!

**Comment by jermnelson** [comment]
@astridu what would the URL be for this functionality? https://sinopia.io/dashboard?

**Comment by jermnelson** [comment]
Issue moved to [LD4P/sinopia_editor #2512](https://github.com/LD4P/sinopia_editor/issues/2512) via [**ZenHub**](https://www.zenhub.com/)

**Comment by astridu** [comment]
@jermnelson Yes, that would be nice!
