### ISSUE TITLE
Saved searches

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#297]
User should be able to save their searches for records or resource templates. This would display at the top of their personalized dashboard. For example:

![image.png](https://images.zenhubusercontent.com/5e13b724f29cd505881d7257/92e678ad-e288-45e4-b9fb-c942c3350b47)

**Comment by justinlittman** [comment]
What does clicking the + do?

**Comment by astridu** [comment]
Takes them to the search page, and on the search page, there would be a button or checkbox that would allow them to save the search. We could either let them name the search or come up with some naming system.

**Comment by justinlittman** [comment]
OK. Do you mind mocking that up? Also, will this UI handle long search names / labels?

**Comment by astridu** [comment]
Of course! I am happy to mock up anything you need. I just wasn't sure which of these things were actual contenders for this work cycle. Mockup coming shortly...
