### ISSUE TITLE
Left column navigation for all sections in a record

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#299]
- Display each section in the left column.
- Each section is clickable. When the section is clicked, section expands to show subsections and that form appears in the right panel. User can enter information in the right panel.
- The section user has clicked or is on is highlighted. (B26F16 for resource templates, 544948 for records/non-resource templates)
- If information is entered in a section, a check mark will appear next to the section and subsection to indicate information has been entered into that section.
- Left nav is anchored on the left, meaning that it always remains at the top, even if the form in the right panel is farther down the page.

![image](https://user-images.githubusercontent.com/42216982/93116715-810c6800-f672-11ea-9383-5b845f4d7fc9.png)

**Comment by astridu** [comment]
Example of field that has multiple values. 
![image](https://user-images.githubusercontent.com/42216982/93254560-60fda700-f74d-11ea-8279-27fbee9080dd.png)

**Comment by justinlittman** [comment]
@astridu How will it look if the values are long?

**Comment by astridu** [comment]
Good question. Could we do something like this where the text wraps until it ends, and we keep the trash/language icons right justified on the last line? 
![image](https://user-images.githubusercontent.com/42216982/93264823-8c3bc280-f75c-11ea-94a4-30e752176601.png)

**Comment by michelleif** [comment]
regarding the original ticket description:
this part does not seem to work:
"When the section is clicked, section expands to show subsections and that form appears in the right panel"
example
https://development.sinopia.io/editor/completely:new

1. scroll to field `Example 18`
2. click field name in left nav
3. expected behavior: subsection title should show in left nav. actual behavior: section title is highlighted, and that section appears in right panel, but subsection title is not shown in left nav or on right panel
![Screen Shot 2020-09-25 at 12.03.15 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/533447fe-ad03-4984-b490-d540f02610f8)
4. if I click "Add" in the right panel to expand, then the left nav does show the subsection
![Screen Shot 2020-09-25 at 12.03.52 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/36704398-81e6-47e4-918f-e9b41e2affdc)

@astridu @justinlittman is the left nav working as expected with respect to subsections?

**Comment by astridu** [comment]
@michelleif I intended it would work the way you describe it in expected behavior.

**Comment by justinlittman** [comment]
There was some talk about automatically expanding panel properties for all panels. However, that really has nothing to do with left nav. If you'd like that done, please ticket separately.

Note that when there are defaults, this is going to mean items are automatically added to the record.

**Comment by michelleif** [comment]
would it make more sense if, when you click a section in the left nav, the left nav expands (if there are subsections), but the right nav doesn't expand until you click one of those subsections in left nav?

**Comment by justinlittman** [comment]
That would be complex to implement.

**Comment by michelleif** [comment]
ok.
regarding expanding everything in right nav, this is documented in #300. I think it would be very useful. @astridu are we going ahead with this? (@jermnelson: this is what I was asking you about) and if so, if everything on right is expanded automatically, then is everything in left nav expanding automatically too? that might reduce the utility of left nav as an overview tool

**Comment by astridu** [comment]
@michelleif Having all sections expanded was definitely one of the requests at the top of the list from catalogers to reduce the amount of clicking (to open each section).

**Comment by michelleif** [comment]
@astridu does that mean left nav should be expanded  automatically as well?

**Comment by astridu** [comment]
No, just the right panel. The left nav should only expand when you click on the section. This is because the left nav is for navigation, while having the right panels open enable quick data entry.

**Comment by michelleif** [comment]
so is this correct?
1) right panel, request enhancement: entire form (right panel) is automatically expanded (we will use existing ticket #300, updating it to be clear)
2) left nav, keep current behavior: left nav does not expand until user clicks a section

follow up: if entire form is automatically expanded, do we need a way to collapse sections? (without trashing the section)? this is discussed in ld4p/sinopia_editor#1249

**Comment by astridu** [comment]
Yes, thank you!

**Comment by astridu** [comment]
A collapse would be nice, but not necessary since we have the left nav to easily/quickly jump to the appropriate place in the form.

**Comment by michelleif** [comment]
closing this ticket
