### ISSUE TITLE
Expand all sections on right panel in Editor

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia#300]
To complement the new left nav, update the right panel of editor to have all sections defaulted open.
- The entirety of the record should appear in the right panel. 
- User can scroll through the whole record on the right, or use the left nav links to go directly to a section.
- Update form fields 

![image.png](https://images.zenhubusercontent.com/5e13b724f29cd505881d7257/ff50734f-3bf4-4c6a-a1b1-a96847ac3617)

**Comment by justinlittman** [comment]
re "update the right panel of editor to have all sections defaulted open": How should defaults be handled?

**Comment by astridu** [comment]
I realize this is different from how we do things now technically, but from a UX perspective, it would be nice to have all the sections open, their defaults filled in, but it doesn't save until they click 'Save'. The checkmarks on the sections that have been filled in will tell them whether there is default content in there so they can decide to delete it if they wanted.

**Comment by justinlittman** [comment]
OK. That's totally do-able. Is this ticket intended solely for functionality changes or for also visual changes (e.g., the style of inputs)?

**Comment by astridu** [comment]
If it's easier, I can create another ticket for visual changes. Does that help?

**Comment by justinlittman** [comment]
Yes, it does help. I'd recommend a discussion with @jermnelson to discuss how proposed visual changes align with bootstrap.

**Comment by jermnelson** [comment]
@astridu, yes a separate ticket for visual changes in the right panel would be helpful so we can break down the UI changes into more discrete  "chunks". I started one ticket that would be belong with this ticket 2401 for change the label for input fields: https://github.com/LD4P/sinopia_editor/issues/2401

**Comment by michelleif** [comment]
This ticket is for the functionality change of having everything open. See Astrid comment Aug 26

**Comment by jermnelson** [comment]
Issue moved to [LD4P/sinopia_editor #2541](https://github.com/LD4P/sinopia_editor/issues/2541) via [**ZenHub**](https://www.zenhub.com/)
