### ISSUE TITLE
Left nav disappears if you Preview from Search and then try to open a Resource Template

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#307]
go to Search, do a search, choose any result and Preview it. 
close the Preview. 
Now go to Resource Templates and open a template for cataloging. 
the left nav is gone. 
hard refresh, the left nav returns

**Comment by michelleif** [comment]
This may be obviated if we do a user-friendly-style preview per #2178

**Comment by jermnelson** [comment]
Issue moved to [LD4P/sinopia_editor #2580](https://github.com/LD4P/sinopia_editor/issues/2580) via [**ZenHub**](https://www.zenhub.com/)
