### ISSUE TITLE
URI for <http://sinopia.io/vocabulary/propertyType/resource> not dereferencing

### ISSUE THREAD

**Issue by briesenberg07** [LD4P/sinopia#310]
“nested resource” properties are assigned <http://sinopia.io/vocabulary/propertyType/resource>, but this IRI doesn’t dereference. 

![iri_assigned](https://user-images.githubusercontent.com/27664966/98591400-0bdd9d80-2285-11eb-95f1-a280b1a3ee61.png)

![image](https://user-images.githubusercontent.com/27664966/98591433-1861f600-2285-11eb-8d4b-66f5f0334c5c.png)

**Comment by briesenberg07** [comment]
Related to #277

**Comment by jermnelson** [comment]
Closing fixed by https://github.com/LD4P/sinopia_editor/pull/2782
