### ISSUE TITLE
Simplify / consolidate / streamline deployment of Sinopia applications

### ISSUE THREAD

**Issue by mjgiarlo** [LD4P/sinopia#314]
We would like to make deploying Sinopia applications easier and/or faster. Currently, it takes more time for us to deploy Sinopia than it does for any of our other projects. Potential aspects of this work:

* Find a way to use fewer systems (DockerHub, CircleCI, GitHub, Terraform/AWS)
* Find a way to leverage Terraform more/better (consult with Ops team)
* Consider approaches / ideas from DLME (consult with Access team)

It would be ideal to discuss this during the first sprint of our next Sinopia work cycle, involving Ops and Access once we have our ducks in a row.

cc: @jermnelson @justinlittman

**Comment by jermnelson** [comment]
WIP - TF simplification proposal in the works.
