### ISSUE TITLE
Create groups and add users to groups in Cognito

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia#320]
* See https://github.com/LD4P/sinopia_editor/blob/main/src/Config.js#L134 for existing groups. The key should be the name and the value should be the description.
* All users should be added to the Public group.
* For Stanford, create a separate group for templates.
* This should be performed in all 3 environments.

**Comment by michelleif** [comment]
this is done in all environments.

for PRD, many users are NOT in a group. awaiting broader discussion of who should be in PRD vs who should be in Stage. Can always add people to Other quickly when needed.
