### ISSUE TITLE
Add help text to fields (or groups of fields) to give guidance to Cataloger

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#36]
A25: Add help text to fields (or groups of fields) to give guidance to Cataloger

i.e. forms should have ability for field-level titles & descriptions to be added.

Also related: A26: In the help text, add hyperlink to external documentation that Catalogers rely on

(i.e. description field should support links)

**Comment by michelleif** [comment]
ideally, allow there to be more than one link in the description/help-text: info from catalogers: in OCLC Connexion, fields can have more than one help link, example: link to the RDA Toolkit rule for a field, or link to OCLC help text for a field

**Comment by michelleif** [comment]
tested that we can provide tooltips as links or as text. have not tested multiple links in one tool tip
