### ISSUE TITLE
Create multi-entity forms

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#38]
A28: Create a form that allows cataloger to enter descriptions of (or link to) Work, Item, and Instance all in one form. In other words: cataloger should be able to describe related entities without having to navigate to different "pages" / forms.

Related to #23 and #37

i.e. ability to create sections that have different default resources / subjects that the assertions apply to

**Comment by michelleif** [comment]
changing title from "multi-value" forms to "multi-entity" forms to make clearer
