### ISSUE TITLE
unit test for entering diacritics

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#46]
C11: Easy entry of diacritics

See errors being encountered here: 

https://github.com/LD4P/requirements/issues/129, https://github.com/LD4P/requirements/issues/116,

**Comment by michelleif** [comment]
Astrid to follow up with Jodi on current state of BFE, how catalogers enter diacritics, whether there are known bugs needing fixing.

re LD4P/requirements#116, adding an IME is out of scope for Work Cycle #1

**Comment by michelleif** [comment]
create input literal test

**Comment by jcoyne** [comment]
Closed by https://github.com/LD4P/sinopia_editor/commit/91c36c0eada116c1ed87b334c2b522821fa7344f
