### ISSUE TITLE
Flexible editor workflow

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia#49]
Needs tech evaluation: 

Flexible workflow, supports various order of metadata creation: 
(1) edit Work, Instance and Item in consolidated form; (2) start with Work, Instance, or Item and be able get to the other forms you need and link among them 

Some discussion on this:
Is this not supporting the ability for users to define the scope of a form / profile according to their workflow needs? i.e. you can have 1 form with Work, Instance, Item; or 3 forms for those separate; and use which you want? Does this put profile requirements on the above for knowing what to populate from previous forms to the next?
Michelle Futornick
Michelle Futornick
11:05 AM Today
being able to define forms/profiles gets at part of this. once you have the forms, say you are working on a form and need to refer to an entity described in another form (a Work URI for example), here's where we want some ease in looking up (finding) that URI and referring to it. as stated elsewhere, an MVP can be look up (find) the URI, copy and paste it where appropriate. to answer the second question, no, there are no requirements on automatically populating things from one form to the next, beyond the part about, look something up and point to / refer to it (with copy/paste or ideally more elegantly later on)

**Comment by michelleif** [comment]
closing this because we satisfy the minimum requirement by ability to create different profiles for different needs; anything further is bluesky and would need rethinking anyway
