### ISSUE TITLE
View metadata in various serializations

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#52]
E2: View metadata in various serializations

MVP: Export option for metadata in multiple serializations. May be more feedback in editor evaluation that changes this.

**Comment by michelleif** [comment]
need to confirm whether existing BFE serializations will still be avail to catalogers in Sinopia:
if so, no need to do anything else.

**Comment by michelleif** [comment]
LC BFE offers the following when you click Preview:
Turtle
JSONLD
RDF-XML
Visualize (don't know where this comes from or how useful)

**Comment by michelleif** [comment]
preview now lets you see N-triples. this is sufficient for viewing. exporting is ticketed elsewhere so I'm closing this.
