### ISSUE TITLE
Work Lookups for Linking / Referencing

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#58]
F7: Allow look-up from and reference to repositories of Works and Instances and Items, wherever those repositories are

Look-up: look-up from and reference to are meant to be the same process, like you look up (find) a work in id.loc.gov Works and "choose" it, then you've referred to it

"wherever those repositories are": repositories would still need to be accessible either via whatever lookup system(s) we have OR field supports the ability to enter a URI copy + pasted in

**Comment by michelleif** [comment]
such as looking up works in LC Works database -- or would that go through Questioning Authority?

**Comment by cmh2166** [comment]
Don't worry about the QA part; this just captures the requirement for the MVP.

**Comment by michelleif** [comment]
from actual user:
example 1:
"I have a new book in hand. I want to find out if that particular instance of the book is already cataloged, so I search via that instance data. If I find someone has already cataloged, I will need to say somehow that my library has a copy of this book."
example 2:
"I have a new book in hand. I searched for an instance but did not find one, so I search for a work (or perhaps I found the work searching for the instance in the first place, but the instance did not match mine). If I find a matching work, I will then create a new instance of that work and say that we own a copy of it."

**Comment by michelleif** [comment]
from another user:
"As a cataloger I can look up against converted MARC data so that i can link to entities, rather than recreate them.”

**Comment by michelleif** [comment]
An example use case for Harvard wikidata/map project: We will have BF descriptions for the paper version of maps that we’ve already cataloged in MARC (will be converted by Casalini to BF), and we want to catalog the digital version in Sinopia, associating it to the paper map Work with an instance-to-work relationship

**Comment by michelleif** [comment]
as long as QA can provide the lookup, we support it.

lookups to Sinopia works in progress
