### ISSUE TITLE
What Levels of Authentication

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia#6]
The default currently for ld4p sandbox dev is: 

* authentication via account creation by anyone on the website; 
* default role for editing + saving; 

to be further worked out;

* who is "anyone"? darsi's kid?

**Comment by cmh2166** [comment]
provenance needed (quad store? to be discussed as part of design review + expansion)
- read: everyone in the world can see everything created; creates onus on people at every institution to strip data they don't want viewable. Possible to be overturned or flexible based on emerging or new user stories.
- create: anyone with an account can create whatever they want, & persist;
- update: MVP is update only stuff that the user themselves made;
- delete: MVP is delete only stuff that the user themselves made;

**Comment by cmh2166** [comment]
Question for Michelle: is the plan currently to stick with basic authentication (i.e. user can create an account, an admin can approve them, then we manage what namespaces that user writes to internally)?

**Comment by ndushay** [comment]
you can login as an admin or as a user (data-creator).  period.  the end.
