### ISSUE TITLE
Add Label or other info with URIs entered

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#60]
F9. When you look up a Work/Instance/Item or authority and then reference it in your metadata, you need to be able to see what you chose in a readable way, not just the URI of what you chose.

Example: when lookup of Agent, grab URI of Agent plus Agent's preflabel

**Comment by michelleif** [comment]
this was discussed in storytime july 15, 2019, determined it requires more research to determine how to pull pref label, there won't always be a pref label, etc. closing this for now as we are going to live with URI only and have the URI be clickable so the cataloger can dereference it

**Comment by michelleif** [comment]
but see https://github.com/LD4P/sinopia_editor/issues/873
