### ISSUE TITLE
Validate entered info at time of entry at field-level; if invalid, get message about why it's invalid

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#62]
I2: Validate entered info at time of entry at field-level; if invalid, get message about why it's invalid

Level of validation dependent on forms' validation support minimum (i.e. this field can only take a text value, maybe not this field is a valid "call number")

**Comment by michelleif** [comment]
we do some field-level validation (like checking that a value is a URI for property type = resource, no referred resource template). we validate all the fields upon save. closing this. we will open separate tickets for specific types of field-level validation when needed (for example, if we start using valuedatatype to specify that a literal should be a date in a certain format, for example)
