### ISSUE TITLE
Entity Creation Support if Look-up Fails

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia#64]
L1. If no entity is available via look-ups, be able to create one in ISNI, NACO, or other established places.

This MVP could be:
1. Link to place where person can create a resource or docs for creation
2. Alternative is they can create local agent (see #65) or other entity in sandbox then sameAs that later

Neither of these negate ability to copy / paste URI into field value.

**Comment by michelleif** [comment]
Harvard needs ability to create entities in Wikidata (especially) and ISNI from the sandbox. Further detail coming.

**Comment by michelleif** [comment]
update: Harvard does not expect to be able to do this in the first work cycle.

**Comment by michelleif** [comment]
duplicate of #65
