### ISSUE TITLE
Entity Creation Support Locally if Look-up Fails

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#65]
L1. If no entity is available via look-ups, be able to create one stored in sandbox.

Later, they could possibly sameAs this to external entities. 

See #64.

**Comment by cmh2166** [comment]
Question: ensure that the data for these entities is then published out for pick up elsewhere (like QA) for reconciliation  & sharing out.

**Comment by michelleif** [comment]
create local agent or other entity in sandbox then sameAs that later
Neither of these negate ability to copy / paste URI into field value.
(this might be repeating comments above but is copied from #64 to make sure captured)

**Comment by michelleif** [comment]
we do have the ability to create a template to establish an entity in sinopia. we also have the ability to enter a URI or literal if lookup fails (there's still some lookup components that don't offer this...those gaps are already ticketed)
