### ISSUE TITLE
Use your proposed entity right away as a provisional entity

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#66]
L2: Use your proposed entity right away.

Removing provisional aspect because no functional requirements in sandbox to carry or act on this type of administrative metadata. 

See #65 See #64

Basically, if creating an entity in local store or external store that support immediate publication, be able to use that URI in the editor via copy paste at the very least; 

look-up support depends on timing of QA or related process retrieval of that new data and support for the source of the entities (i.e. wikidata)

**Comment by michelleif** [comment]
out of scope for Work Cycle #1, this falls under "seamless creation of external entities while working in Sinopia"

**Comment by michelleif** [comment]
we are not doing any kind of integration with proposing new entities to external sources, so this is out of scope.
