### ISSUE TITLE
Allow SameAs

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#68]
Other2: SameAs assertions among local entities and between local entities and external entities

MVP: for certain, batch update can include skos or whatever sameAs

MVP? / Needs more use case analysis: sameAs supported as a default editor action across profiles. What actions would we want to support?

More use cases: 
--Two Works are recognized as being the same 
--Two people simultaneously create authority records for the same author

**Comment by michelleif** [comment]
closing. no use case currently. if someone wants to declare a SameAs they can add a field to their template for that.
