### ISSUE TITLE
Get sample BIBFRAME Profiles for dev usage

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia#7]
Doesn't mean we're stuck with these, but give devs a place to start

**Comment by michelleif** [comment]
here are the latest BF profiles from LC: https://github.com/lcnetdev/bfe/tree/master/static/profiles/bibframe

**Comment by cmh2166** [comment]
Great. @jgreben & @jermnelson - this looks sufficient?

**Comment by jgreben** [comment]
Looks good for now!

**Comment by kirkhess** [comment]
The profiles are stored in Verso now. The are loaded from the data/profiles directory:
https://github.com/lcnetdev/verso/tree/master/data/profiles

**Comment by jermnelson** [comment]
The Verso Profiles should be sufficient enough to close this ticket.
