### ISSUE TITLE
Data Locking...?

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#71]
Discuss among tech team what locking should occur, how, when, based on data requirements for editor to system to downstream systems as understood, gathered, analyzed

**Comment by cmh2166** [comment]
Related discussion point for this: "Necessary to avoid data corruption in an environment with multiple simultaneous users. Sends confirmation of changes, or notification of failure. No partial successes on change operations."

**Comment by michelleif** [comment]
@jermnelson @justinlittman do we need to account for the possibility of two people editing the same entity simultaneously? currently we would just save the changes of whoever hit save first? and not inform the other user that changes were made?

**Comment by justinlittman** [comment]
I'd suggest that any sort of a locking scheme has (1) not been requested by users; (2) is outside the scope of the current grant; and (3) would require an effort that would not fit into upcoming work cycle. This would be a good candidate for a future grant. If you disagree with closing, feel free to reopen.
