### ISSUE TITLE
Do not litter in triplestore

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#72]
We think that "in the shared environment" here means not putting artifacts or non-resource-metadata into the triplestore. We'll need to store some of this information in our "sandbox", e.g. authentication layer, or the provenance / history stream.

"Does not record editor-specific information in the shared environment.

Does not record session-specific information in the shared environment.

can we get a testable example of littering?"

**Comment by michelleif** [comment]
give a hoot. don't pollute.
