### ISSUE TITLE
Notify user data has changed during their editor session

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#73]
If the RDF store uses optimistic locking:

The editor must inform the user that there is a conflict. 

The editor must give the user enough information to understand the specifics of the conflict, and to decide on how to resolve the conflict. 

The editor must allow the user to select and commit the desired resolution.the resolution.

See also #71

**Comment by justinlittman** [comment]
I'd suggest that any sort of a locking or notification scheme has (1) not been requested by users; (2) is outside the scope of the current grant; and (3) would require an effort that would not fit into upcoming work cycle. This would be a good candidate for a future grant. If you disagree with closing, feel free to reopen.
