### ISSUE TITLE
User can enter UNICODE characters without corruption. (non-Roman, non-Latin, right-to-left)

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#74]
Editor must allow entering, storage, and retrieval of all UNICODE characters without corruption.

Right to left text handling as well.

**Comment by michelleif** [comment]
need to test that the info comes out ok in the RDF

**Comment by michelleif** [comment]
Chinese works, just need to test right-to-left

**Comment by michelleif** [comment]
this is tracked in UAT ticket for milestone 4 so closing
