### ISSUE TITLE
filter editor search responses to creator / source or other fields

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#76]
i.e. "I only want PCC entities to be returned in an editor search for copy cataloging purposes."

Possibly same as #51

**Comment by michelleif** [comment]
just saying show from xyz library is not enough because even PCC libraries, incl Stanford, are interested in putting in non-PCC data in the sandbox. . How will we know what is PCC compliant? There’s coding in MARC that tells you it’s PCC. Big question: what does PCC-compliance mean in RDF world?

**Comment by michelleif** [comment]
Not changing the use case. Just adding detail, because at one point we thought that if we could filter by institution that created the statements, that would suffice. To make it clear that "PCC entity(?)" does not equal "entity created by PCC institution"

**Comment by michelleif** [comment]
we don't have the concept of a PCC record now.
