### ISSUE TITLE
UX changes for ease of editor use without dragging

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#86]

**Comment by michelleif** [comment]
ease of use without clicking (i.e., be able to tab through everything / all fields) is already documented in #47.

ease of use regarding having to drag submenus around is not in scope for Work Cycle #1 so moving this ticket to future, and renaming to take out the part about clicking

**Comment by michelleif** [comment]
I think this is fixed with Jeremy's revised UI design.
