### ISSUE TITLE
Discogs Use Case

### ISSUE THREAD

**Issue by cmharlow** [LD4P/sinopia#98]
No Cornell requirement for Sinatra for having data within Sinopia; early analysis on the collection of 45’s suggests there isn’t much MARC available. Discogs has better coverage. Our goal is to lessen the amount of cutting and pasting catalogers have to do between discogs and editor environment.

**Comment by michelleif** [comment]
more info from a slack discussion september 2018:

steven f: Where the lookup and conversion happens is still being discussed, but the idea is that one way or another, the data would get into Sinopia for editing. It could be an external process where we upload the data, or this could be a mapper use case. (As much as I understand the mapper discussion.) I’m not a manager, but my understanding is we have devs to devote to this effort. How they might work with the core Sinopia devs is unclear to me.

zimeon [7:54 AM]
^ I think given timeline of core sinopia dev work and importance of meeting April goals, our work on import from Discogs cannot be a close collaboration with core dev. However, it will be useful to understand parameters as they will impact others as well as us

**Comment by michelleif** [comment]
covered by #95
